apiVersion: apps/v1
kind: Deployment
metadata:
  name: k3s-demo
  namespace: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k3s-demo
  template:
    metadata:
      labels:
        app: k3s-demo
    spec:
      containers:
      - name: k3s-demo
        image: ruanbekker/rpi-hostname:latest
---
apiVersion: v1
kind: Service
metadata:
  name: k3s-demo
  namespace: demo
spec:
  ports:
  - name: http
    targetPort: 8000
    port: 80
  selector:
    app: k3s-demo
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: k3s-demo
  namespace: demo
spec:
  ingressClassName: nginx
  rules:
  - host: demo.mmarquet.giize.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: k3s-demo
            port:
              name: http
